### ISSUE TITLE
Have some binary releases

### ISSUE THREAD

**Issue by Xylemon** [Xylemon/xlennart#6]
For 1.1 I would like there to be some packages for at least two distros. I think I'll take a look at making a SlackBuild script and package along with a Debian package. If anyone wants to make any packages for another distro or OS that would be great.

**Comment by xaionaro** [comment]
An answer from Debian:

> That sounds like a lot of code duplication. Is it possible to have a
> common library between XBill and XLennart?
> 
> (Also, in any case, don't you think that this game is going a little too
> far? It's fine to be opposed to systemd, but don't do to Lennart
> Poettering what the gamergate people did to Anita Sarkeesian.)

**Comment by Xylemon** [comment]
@xaionaro I read some of the responses and such, and I appreciate your package request and responses to those who seem very bothered by it. If it's accepted to be in the Debian repos, we should use @Centuriondan awesome package. I'm going to try to get back to XLennart and prepare everything for the next release sometime this week or so.

**Comment by xaionaro** [comment]
@Xylemon, seems Debian won't permit this… But let's see.

If somebody interested, the discussion is here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775436

**Comment by xaionaro** [comment]
@Xylemon, there's an idea to merge XLennart with XBill and other x-persons and rename it to something like "XPerson". What do you think?

The original text from debian-devel:
>>> I'd also object on the technical grounds that we already have xbill and
>>> the changes in xlennart don't truly justify a fork.
>>
>> This could be easily solved by merging xbill with xlennart to "xperson"
>> with collection of this people (bill and lennart).
> 
> I've already seen this kind of xbill clone with other people (not
> FOSS-related). It makes sense and would be fun to be able to easily
> choose the games sprites among an easily-extensible list.

**Comment by Xylemon** [comment]
@xaionaro It's an interesting idea, but it sounds like a fork of XBill with modding support. I personally don't think that would be necessarily appropriate for this project. This project may evolve into something bigger eventually (someone was/is considering adding SDL support and I think some type of mulitplayer would be interesting), but for now I think it's best for XLennart just to be it's own thing.
